# Generated by Django 2.2 on 2019-04-16 20:16

from django.db import migrations, models
import updates.models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0002_remove_update_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=updates.models.upload_update_image),
        ),
    ]
