# Generated by Django 2.2 on 2019-04-19 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_auto_20190419_0726'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'Status posts'},
        ),
    ]
