# Generated by Django 2.2 on 2019-04-19 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0003_auto_20190419_0728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Status post'},
        ),
    ]
