# Generated by Django 2.2 on 2019-04-19 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0004_auto_20190419_0729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={},
        ),
    ]
